object Versions {
    const val ANDROIDX_CORE ="1.7.0"
    const val APPCOMPAT = "1.4.0"
    const val MATERIAL = "1.4.0"
    const val CONSTRAINT_LAYOUT ="2.1.2"
    const val ANDROIDX_LEGACY_SUPPORT="1.0.0"
    const val VIEWPAGER2 ="1.0.0"
    const val NAVIGATION_COMPONENT="2.4.0-beta02"
    const val DOTS_INDICATOR = "4.2"
    const val RETROFIT2="2.9.0"
    const val GSON_CONVERTER="2.9.0"
    const val OKHTTP="4.9.3"
    const val LIFECYCLE_EXT="2.2.0"
    const val FRAGMENT_KTX = "1.4.0"
    const val LIFECYCLE_VIEWMODEL="2.4.0"
    const val ACTIVITY_KTX="1.4.0"
    const val DAGGER_HILT="2.38.1"
    const val HILT_LIFECYCLE_VIEWMODEL="1.0.0-alpha03"
    const val PAGING="3.1.0"
    const val GLIDE="4.12.0"
    const val GLIDE_COMPILER="4.12.0"
    const val LOGGING_INTERCEPTOR="4.9.3"
    const val DATASTORE_PREFERENCES="1.0.0"
    //classpath
    const val TOOLS_BUILD_GRADLE="7.0.4"
    const val KOTLIN_GRADLE_PLUGIN="1.6.10"
    const val NAVIGATION_SAFE_ARGS="2.4.0-beta02"
    const val KTLINT_VERSION ="10.2.1"
    //test
    const val JUNIT="4.13.1"
    const val EXT_JUNIT="1.1.3"
    const val ESPRESSO_CORE="3.4.0"

}